config/routes.rb
Rails.application.routes.draw do
  
  devise_for :user,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }
  
  scope module: :public do
    root to:'homes#top'
    get '/my_page' => 'users#mypage'
    
    resources :users, only: [:edit, :show, :update] do
      member do
        get :favorite
      end
    end
    
    resources :posts, only: [:index, :show] do
      resources :comments
      resource :favorite, only: [:create, :destroy]
    end
    
    resources :groups do
      resource :group_user, only: [:create, :destroy]
    end
    
    resources :requests
    
  end
  
  devise_scope :user do
    post "users/guest_sign_in" , to: "public/sessions#guest_sign_in"
  end
  
  devise_for :admin, skip: [:registrations] ,controllers: {
  sessions: "admin/sessions"
  }
  
  namespace :admin do
    root to:'homes#top'
    resources :posts do
       resources :procedures
    end
    resources :comments
    resources :departments, only: [:index, :create, :edit, :update, :destroy]
    resources :occupations, only: [:index, :create, :edit, :update, :destroy]
    resources :categories, only: [:index, :create, :edit, :update, :destroy]
    resources :users, only: [:index, :show, :edit, :update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  
  has_many :posts, dependent: :destroy
  has_many :requests, dependent: :destroy
  
  validates :name, presence: true
  
end

app/models/comment.rb
class Comment < ApplicationRecord
  
  belongs_to :user
  belongs_to :post
  
end

app/models/department.rb
class Department < ApplicationRecord
  
  has_many :users, dependent: :destroy
  
  validates :name, presence: true
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :post
  
end

app/models/group.rb
class Group < ApplicationRecord
  
  has_many :group_users, dependent: :destroy
  
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  
  belongs_to :user
  belongs_to :group
  
end

app/models/occupation.rb
class Occupation < ApplicationRecord
  
  has_many :users, dependent: :destroy
  
  validates :name, presence: true
  
end

app/models/post.rb
class Post < ApplicationRecord
  
  belongs_to :category
  
  has_many :procedures, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  has_many_attached :files
  
  validates :category_id, presence: true
  validates :title, presence: true
  validates :body, presence: true
  validates :level, presence: true
  validates :status, presence: true
  
  enum level: { Beginner: 0, Intermediate: 1, Advanced: 2, Pro: 3 }
  enum status: { Draft: 0, Awaiting_approval: 1, Publish: 2 }
  
end

app/models/procedure.rb
class Procedure < ApplicationRecord
  
  belongs_to :post
  
  has_one_attached :image
  
  validates :procedure_number, presence: true
  validates :title, presence: true
  validates :explain, presence: true
  
end

app/models/request.rb
class Request < ApplicationRecord
  
  belongs_to :user
  belongs_to :category


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         
  belongs_to :department
  belongs_to :occupation
  
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :group_users, dependent: :destroy
  has_many :requests, dependent: :destroy
  
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :ensure_post, only: [:edit, :update, :show, :destroy]
  
  def new
    @post = Post.new
  end
  
  def index
    @posts = Post.all
  end
  
  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to admin_post_path(@post), notice: "投稿完了"
    else
      flash.now[:alert] = "投稿に失敗しました。"
      render :new
    end
  end
  
  def show
  end
  
  def edit
  end
  
  def update
    if @post.update(post_params)
      redirect_to admin_post_path, notice: "更新完了"
    else
      flash[:alert] = "更新失敗"
      redirect_to request.referer
    end
  end



  private
  
  def ensure_post
    @post = Post.find(params[:id])
  end
  
  def post_params
    params.require(:post).permit(:category_id, :title, :body, :level, :status, :files)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/departments_helper.rb
module Admin::DepartmentsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/procedures_helper.rb
module Admin::ProceduresHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/posts/_form.html.erb
<%= form_with model: post, url: url do |f| %>
  <table>
    <tbody>
      <tr>
        <th>タイトル</th>
        <td>
          <%= f.text_field :title %>
        </td>
      </tr>
      <tr>
        <th>カテゴリー</th>
        <td>
          <%= f.collection_select :category_id, Category.all, :id, :name, {include_blank: "--選択してください"} %>
        </td>
      <tr>
        <th>難易度</th>
        <td>
          <%= f.select :level, Post.levels_i18n.invert %>
        </td>
      </tr>
      <tr>
        <th>公開ステータス</th>
        <td>
          <%= f.select :status, Post.statuses_i18n.invert %>
        </td>
      </tr>
      <tr>
        <th>本文</th>
        <td>
          <%= f.text_area :body, size: "100x10" %>
        </td>
      </tr>
      <tr>
        <td>
          <%= f.submit submit %>
        </td>
      </tr>
    </tbody>
  </table>
  <% end %>

app/views/admin/posts/edit.html.erb
<div class="container">
  <h1>マニュアル編集</h1>
  <div class='row'>
    <div class="col my-5">
      <%= render 'form', post: @post ,url: admin_post_path, submit: '変更' %>
    </div>
  </div>
</div>

app/views/admin/posts/index.html.erb
<div class="container">
  <h1>マニュアル一覧</h1>
  <div class='row'>
    <div class="col my-5">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>タイトル</th>
              <th>カテゴリー</th>
              <th>レベル</th>
              <th>リリース状況</th>
              <th>詳細</th>
              <th>編集</th>
            </tr>
          </thead>
          <% @posts.each do |post| %>
          <tbody>
            <tr>
              <td><%= post.title %></td>
              <td><%= post.category.name %></td>
              <td><%= post.level_i18n %></td>
              <td><%= post.status_i18n %></td>
              <th><%= link_to "詳細",admin_post_path(post) %></th>
              <th><%= link_to "編集",edit_admin_post_path(post) %></th>
            </tr>
          </tbody>
          <% end %>
        </table>
    </div>
  </div>
</div>

app/views/admin/posts/new.html.erb
<div class="container">
  <h1>新規登録</h1>
  <div class='row'>
    <div class="col my-5">
      <%= render 'form', post: @post ,url: admin_posts_path, submit: '登録' %>
    </div>
  </div>
</div>

app/views/admin/posts/show.html.erb
<div class="container">
  <h1><%= @post.title %>のマニュアル</h1>
  <h1>
    <%= link_to new_admin_post_procedure_path(@post) do %>
      <i class="fa-solid fa-circle-plus"></i>
    <% end %>
  </h1>
  <div class='row'>
    <div class="col my-5">
      <table class="table table-responsive">
        <tbody>
          <tr>
            <th class="w-25">概要</th>
            <td><%= @post.body %></td>
          </tr>
          <tr>
            <th>カテゴリー</th>
            <td><%= @post.category.name %></td>
          </tr>
          <tr>
            <th>レベル</th>
            <td><%= @post.level_i18n %></td>
          </tr>
          <tr>
            <th>リリース状況</th>
            <td><%= @post.status_i18n %></td>
          </tr>
          <tr>
            <th><%= link_to "編集",edit_admin_post_path(@post) %></th>
            <td></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class='row'>
    <div class="col my-5">
      <% @post.procedures.each do |procedure| %>
        <h2>
          <%= link_to admin_post_procedure_path(@post,procedure) do %>
          手順<%= procedure.procedure_number %>
          <% end %>
          <%= link_to edit_admin_post_procedure_path(@post,procedure) do %>
            <i class="fa-solid fa-pencil"></i>
          <% end %>
        </h2>
        <p><%= procedure.title %></p>
        <p><%= procedure.explain %></p>
         <%= image_tag procedure.image %>
      <% end %>
    </div>
  </div>
</div>