config/routes.rb
Rails.application.routes.draw do
  
  devise_for :user,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }
  
  scope module: :public do
    root to:'homes#top'
    get '/my_page' => 'users#mypage'
    
    resources :users, only: [:edit, :show, :update] do
      member do
        get :favorite
      end
    end
    
    resources :posts, only: [:index, :show] do
      resources :comments
      resource :favorite, only: [:create, :destroy]
    end
    
    resources :groups do
      resource :group_user, only: [:create, :destroy]
    end
    
    resources :requests
    
  end
  
  devise_scope :user do
    post "users/guest_sign_in" , to: "public/sessions#guest_sign_in"
  end
  
  devise_for :admin, skip: [:registrations] ,controllers: {
  sessions: "admin/sessions"
  }
  
  namespace :admin do
    root to:'homes#top'
    resources :posts do
       resources :procedures
    end
    resources :comments
    resources :departments, only: [:index, :create, :edit, :update, :destroy]
    resources :occupations, only: [:index, :create, :edit, :update, :destroy]
    resources :categories, only: [:index, :create, :edit, :update, :destroy]
    resources :users, only: [:index, :show, :edit, :update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  
  has_many :posts, dependent: :destroy
  has_many :requests, dependent: :destroy
  
  validates :name, presence: true
  
end

app/models/comment.rb
class Comment < ApplicationRecord
  
  belongs_to :user
  belongs_to :post
  
end

app/models/department.rb
class Department < ApplicationRecord
  
  has_many :users, dependent: :destroy
  
  validates :name, presence: true
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :post
  
end

app/models/group.rb
class Group < ApplicationRecord
  
  has_many :group_users, dependent: :destroy
  
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  
  belongs_to :user
  belongs_to :group
  
end

app/models/occupation.rb
class Occupation < ApplicationRecord
  
  has_many :users, dependent: :destroy
  
  validates :name, presence: true
  
end

app/models/post.rb
class Post < ApplicationRecord
  
  belongs_to :category
  
  has_many :procedures, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  has_many_attached :files
  
  validates :category_id, presence: true
  validates :title, presence: true
  validates :body, presence: true
  validates :level, presence: true
  validates :status, presence: true
  
  enum level: { Beginner: 0, Intermediate: 1, Advanced: 2, Pro: 3 }
  enum status: { Draft: 0, Awaiting_approval: 1, Publish: 2 }
  
end

app/models/procedure.rb
class Procedure < ApplicationRecord
  
  belongs_to :post
  
  has_one_attached :image
  
  validates :procedure_number, presence: true
  validates :title, presence: true
  validates :explain, presence: true
  
end

app/models/request.rb
class Request < ApplicationRecord
  
  belongs_to :user
  belongs_to :category


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         
  belongs_to :department
  belongs_to :occupation
  
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :group_users, dependent: :destroy
  has_many :requests, dependent: :destroy
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_header.html.erb
<header class="shadow-sm", style="background-color: #3282F6;" >
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container">
      <%= link_to 'Manuals', root_path, class:"navbar-brand text-white" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
              <li><%= link_to 'マニュアル作成',new_admin_post_path, class: 'nav-link text-white' %></li>
              <li><%= link_to 'マニュアル一覧',admin_posts_path, class: 'nav-link text-white' %></li>
              <li><%= link_to '部署',admin_departments_path, class: 'nav-link text-white' %></li>
              <li><%= link_to '職種',admin_occupations_path, class: 'nav-link text-white' %></li>
              <li><%= link_to 'カテゴリー',admin_categories_path, class: 'nav-link text-white' %></li>
              <li><%= link_to 'ログアウト',destroy_admin_session_path, method: :delete, class: 'nav-link text-white' %></li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Manuals</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/f4a6fb0793.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>