config/routes.rb
Rails.application.routes.draw do
  
  devise_for :user,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }
  
  scope module: :public do
    root to:'homes#top'
    get '/my_page' => 'users#mypage'
    
    resources :users, only: [:edit, :show, :update] do
      member do
        get :favorite
      end
    end
    
    resources :posts, only: [:index, :show] do
      resources :comments
      resource :favorite, only: [:create, :destroy]
    end
    
    resources :groups do
      resource :group_user, only: [:create, :destroy]
    end
    
    resources :requests
    
  end
  
  devise_scope :user do
    post "users/guest_sign_in" , to: "public/sessions#guest_sign_in"
  end
  
  devise_for :admin, skip: [:registrations] ,controllers: {
  sessions: "admin/sessions"
  }
  
  namespace :admin do
    root to:'homes#top'
    resources :posts do
       resources :procedures
    end
    resources :comments
    resources :departments, only: [:index, :create, :edit, :update, :destroy]
    resources :occupations, only: [:index, :create, :edit, :update, :destroy]
    resources :categories, only: [:index, :create, :edit, :update, :destroy]
    resources :users, only: [:index, :show, :edit, :update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  
  has_many :posts, dependent: :destroy
  has_many :requests, dependent: :destroy
  
  validates :name, presence: true
  
end

app/models/comment.rb
class Comment < ApplicationRecord
  
  belongs_to :user
  belongs_to :post
  
end

app/models/department.rb
class Department < ApplicationRecord
  
  has_many :users, dependent: :destroy
  
  validates :name, presence: true
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :post
  
end

app/models/group.rb
class Group < ApplicationRecord
  
  has_many :group_users, dependent: :destroy
  
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  
  belongs_to :user
  belongs_to :group
  
end

app/models/occupation.rb
class Occupation < ApplicationRecord
  
  has_many :users, dependent: :destroy
  
  validates :name, presence: true
  
end

app/models/post.rb
class Post < ApplicationRecord
  
  belongs_to :category
  
  has_many :procedures, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  has_many_attached :files
  
  validates :category_id, presence: true
  validates :title, presence: true
  validates :body, presence: true
  validates :level, presence: true
  validates :status, presence: true
  
  enum level: { Beginner: 0, Intermediate: 1, Advanced: 2, Pro: 3 }
  enum status: { Draft: 0, Awaiting_approval: 1, Publish: 2 }
  
end

app/models/procedure.rb
class Procedure < ApplicationRecord
  
  belongs_to :post
  
  has_one_attached :image
  
  validates :procedure_number, presence: true
  validates :title, presence: true
  validates :explain, presence: true
  
end

app/models/request.rb
class Request < ApplicationRecord
  
  belongs_to :user
  belongs_to :category


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         
  belongs_to :department
  belongs_to :occupation
  
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :group_users, dependent: :destroy
  has_many :requests, dependent: :destroy
  
end

app/controllers/admin/procedures_controller.rb
class Admin::ProceduresController < ApplicationController
  before_action :ensure_procedure, only: [:edit, :update, :show, :destroy]
  before_action :ensure_post, only: [:index, :update, :show]
  
  def new
    @procedure = Procedure.new
  end
  
  
  def create
    post = Post.find(params[:post_id])
    @procedure = Procedure.new(procedure_params)
    @procedure.post_id = post.id
    if @procedure.save
      redirect_to admin_post_path(params[:post_id]), notice: "投稿完了"
    end
  end
  
  def index
    @procedures = @post.procedures
  end
  
  def show
  end
  
  def update
    if @procedure.update(procedure_params)
      redirect_to admin_post_path(@post), notice: "更新完了"
    else
      flash.now[:alert] = "Failed to save"
      render :edit
    end
  end
  
  def destroy
    @procedure.destroy
    redirect_to admin_post_path(params[:post_id])
  end
  
  private
  
  def ensure_procedure
    @procedure = Procedure.find(params[:id])
  end
  
  def ensure_post
    @post = Post.find(params[:post_id])
  end
  
  def procedure_params
    params.require(:procedure).permit(:post_id, :procedure_number, :title, :explain, :image)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/departments_helper.rb
module Admin::DepartmentsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/procedures_helper.rb
module Admin::ProceduresHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/procedures/_form.html.erb
<%= form_with model: procedure, url: url, local: true do |f| %>
  <table>
    <tbody>
      <tr>
        <th>
          <h4>手順番号</h4>
        </th>
        <td>
          <%= f.number_field :procedure_number %>
        </td>
      </tr>
      <tr>
        <th>
          <h4>タイトル</h4>
        </th>
        <td>
          <%= f.text_field :title %>
        </td>
      </tr>
      <tr>
        <th>
          <h4>説明</h4>
        </th>
        <td>
          <%= f.text_area :explain %>
        </td>
      </tr>
      <tr>
        <th>
          <h4>画像</h4>
        </th>
        <td>
          <%= f.file_field :image %>
        </td>
      </tr>
      <tr>
        <th><%= f.submit submit %></th>
      </tr>
    </tbody>
  </table>
  <% end %>

app/views/admin/procedures/edit.html.erb
<h1>工程修正</h1>
<%= render 'form', post: @post,procedure: @procedure ,url: admin_post_procedure_path, submit: '変更' %>
<%= link_to '削除する', admin_post_procedure_path(@procedure.post,@procedure), method: :delete, data: {confirm: '本当に削除しますか？'} %>

app/views/admin/procedures/new.html.erb
<h1>工程登録</h1>
<%= render 'form', post: @post,procedure: @procedure ,url: admin_post_procedures_path, submit: '登録' %>

app/views/admin/procedures/show.html.erb
<h1>手順<%= @procedure.procedure_number %>
  <%= link_to edit_admin_post_procedure_path(@post,@procedure) do %>
    <i class="fa-solid fa-pencil"></i>
  <% end %>
  <%= link_to admin_post_procedure_path(@procedure.post,@procedure), method: :delete, data: {confirm: '本当に削除しますか？'} do %>
    <i class="fa-solid fa-trash-can"></i>
  <% end %>
</h1>
<h3><%= @procedure.title %></h3>
<%= @procedure.explain %></br>
<%= image_tag @procedure.image %>